formatters:
  simple:
    format: '%(asctime)s %(name)s [%(levelname)s]: %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    stream: ext://sys.stdout

root:
  handlers: [console]

model:
  name: MegaMolBART
  # name: CDDD
  params:
    url: localhost:50051

metric:
  validity:
    enabled: True
    input_size: 20000
    radius:
      - 1
      # - 2

  unique:
    enabled: True
    input_size: ${metric.validity.input_size}
    remove_invalid: True
    radius: ${metric.validity.radius}

  novelty:
    enabled: True
    input_size: ${metric.validity.input_size}
    remove_invalid: True
    radius: ${metric.validity.radius}

  nearest_neighbor_correlation:
    enabled: True
    input_size: -1
    top_k:
      - 50
      - 100
      - 500

  modelability:
    physchem:
      enabled: True
      input_size: -1
      n_splits: 20
      return_predictions: True

    bioactivity:
      enabled: True
      input_size: 10 # Number of genes to include, not number of molecules, -1 is all genes
      n_splits: 20
      return_predictions: True

sampling:
  max_seq_len: 512
  sample_size: 10

output:
  path: /data/benchmark_output/
