formatters:
  simple:
    format: '%(asctime)s %(name)s [%(levelname)s]: %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    stream: ext://sys.stdout

root:
  handlers: [console]

model:
  # Please change following properties when changing model.name
  #   - sampling.concurrent_requests
  #   - model.params.url (50052 for lb grpc)
  # name: CDDD
  # training_data: /data/db/cddd_train.sqlit

  name:  cuchembm.inference.GrpcMegaMolBARTWrapper
  training_data: /data/db/zinc_train.sqlite3
  params:
    url: nginx:50052

sampling:
  max_seq_len: 512
  sample_size: 10
  db: /data/db/embedding_cache_2.sqlite3
  concurrent_requests: 10

output:
  path: /data/benchmark_output_test/

metric:
  validity:
    enabled: False
    input_size: 20000
    radius:
      - 1
      # - 2

  unique:
    enabled: True
    input_size: ${metric.validity.input_size}
    remove_invalid: False
    radius: ${metric.validity.radius}

  novelty:
    enabled: True
    input_size: ${metric.validity.input_size}
    remove_invalid: True
    radius: ${metric.validity.radius}

  nearest_neighbor_correlation:
    enabled: True
    input_size: -1
    top_k:
      - 50
      - 100
      - 500

  modelability:
    physchem:
      enabled: True
      input_size: 10000
      n_splits: 20
      normalize_inputs: True
      return_predictions: True

    bioactivity:
      enabled: True
      input_size: 10000 # Number of genes to include, not number of molecules, -1 is all genes
      gene_cnt: 10
      n_splits: 20
      normalize_inputs: True
      return_predictions: True
