# Copyright 2020 NVIDIA Corporation
FROM rapidsai/rapidsai:22.02-cuda11.4-base-ubuntu20.04-py3.8

RUN apt-get update \
    && apt-get upgrade -y \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y wget git unzip tmux \
        apt-transport-https \
        ca-certificates \
        curl \
        gnupg \
        lsb-release \
    && rm -rf /var/lib/apt/lists/*

SHELL ["conda", "run", "-n", "rapids", "/bin/bash", "-c"]
RUN pip install rdkit-pypi==2021.9.5.1
# conda install -y -c conda-forge -n rapids rdkit==2020.09.1.0

COPY ./ /opt/nvidia/cheminfomatics
RUN pip install -r /opt/nvidia/cheminfomatics/common/requirements.txt
RUN pip install -r /opt/nvidia/cheminfomatics/cuchem/requirements.txt

# WAR for dash breaking due to werkzeug incompatibility
RUN pip install --upgrade werkzeug==2.0.3

ENV UCX_LOG_LEVEL error
ENV PYTHONPATH ./common/generated:./common:./cuchem:
WORKDIR /opt/nvidia/cheminfomatics
CMD cd /opt/nvidia/cheminfomatics; ./launch.sh start
