version: 1
exp_name: mim_k1_salv
model:
  name: nemo_chem.models.megamolbart.NeMoMegaMolBARTWrapper
  display_name: nemo_chem
  checkpoint_file: /models/megamolbart/Small_Span_Aug_2f63a83b_220424.nemo
  training_data: /data/db/zinc_train.sqlite3
  batch_size: 100 # 100 for seq2seq radii > 1 batch_size of 500 is too much for single GPU
  perceiver_average: False
  noise_mode: 2 # For LVM sampling selection default 0
  average_tokens: True

sampling:
  max_seq_len: 512
  sample_size: 10
  db: /data/db/${exp_name}.sqlite3
  concurrent_requests: 10
  radius:
    - 0.1
    - 0.3
    - 0.5
    - 0.7
    - 0.9
    - 1.1
    - 1.3
    - 1.5
    - 1.7
    - 1.9
    - 2.1
    - 2.3
    - 2.5

output:
  path: /data/benchmark_output/nemo

metrics:
  validity:
    impl: chembench.metrics.Validity
    datasets:
      - file: /workspace/cheminformatics/benchmark/csv_data/benchmark_ZINC15_test_split.csv
        smis_col: canonical_smiles
        type: SAMPLE
        input_size: 1000
        label: sample_ds
    enabled: False

  unique:
    impl: chembench.metrics.Unique
    datasets: ${metrics.validity.datasets}
    enabled: False
    remove_invalid: False

  novelty:
    impl: chembench.metrics.Novelty
    datasets: ${metrics.validity.datasets}
    enabled: False
    remove_invalid: False

  effective_novelty:
    impl: chembench.metrics.EffectiveNovelty
    datasets: ${metrics.validity.datasets}
    enabled: False
    remove_invalid: False

  non_identicality:
    impl: chembench.metrics.NonIdenticality
    datasets: ${metrics.validity.datasets}
    enabled: False
    remove_invalid: False

  scaffold_unique:
    impl: chembench.metrics.ScaffoldUnique
    datasets: ${metrics.validity.datasets}
    enabled: False
    remove_invalid: False

  scaffold_non_identical_similarity:
    impl: chembench.metrics.ScaffoldNonIdenticalSimilarity
    datasets: ${metrics.validity.datasets}
    enabled: False
    remove_invalid: False
    nbits: 2048

  nearest_neighbor_correlation:
    impl: chembench.metrics.NearestNeighborCorrelation
    datasets:
      - file: /workspace/cheminformatics/benchmark/csv_data/benchmark_ChEMBL_approved_drugs_physchem.csv
        impl: chembench.datasets.base.GenericCSVDataset
        properties_cols:
          - max_phase_for_ind
          - mw_freebase
          - alogp
          - hba
          - hbd
          - psa
          - rtb
          - ro3_pass
          - num_ro5_violations
          - cx_logp
          - cx_logd
          - full_mwt
          - aromatic_rings
          - heavy_atoms
          - qed_weighted
          - mw_monoisotopic
          - hba_lipinski
          - hbd_lipinski
          - num_lipinski_ro5_violations
        smis_col: canonical_smiles
        type: EMBEDDING
        input_size: null
        label: chembl
    enabled: False
    top_k:
      - 50
      - 100
      - 500

  physchem_lipophilicity:
    impl: chembench.metrics.Modelability
    datasets:
      - file: /workspace/cheminformatics/benchmark/csv_data/benchmark_MoleculeNet_Lipophilicity.csv
        impl: chembench.datasets.base.GenericCSVDataset
        label: lipophilicity
        index_col: index
        smis_col: SMILES
        properties_cols:
          - logD
        orig_property_name:
          - exp
        type: EMBEDDING
        input_size: null
    enabled: False
    n_splits: 20
    nbits: 512
    normalize_inputs: True
    return_predictions: True

  physchem_esol:
    impl: chembench.metrics.Modelability
    datasets:
      - file: /workspace/cheminformatics/benchmark/csv_data/benchmark_MoleculeNet_ESOL.csv
        impl: chembench.datasets.base.GenericCSVDataset
        label: esol
        index_col: index
        smis_col: SMILES
        properties_cols:
          - 'log_solubility_(mol_per_L)'
        orig_property_name:
          - measured log solubility in mols per litre
        type: EMBEDDING
        input_size: null
    enabled: False
    n_splits: 20
    nbits: 512
    normalize_inputs: True
    return_predictions: True

  physchem_freesolv:
    impl: chembench.metrics.Modelability
    datasets:
      - file: /workspace/cheminformatics/benchmark/csv_data/benchmark_MoleculeNet_FreeSolv.csv
        impl: chembench.datasets.base.GenericCSVDataset
        label: freesolv
        index_col: index
        smis_col: SMILES
        properties_cols:
          - hydration_free_energy
        orig_property_name:
          - y
        type: EMBEDDING
        input_size: null
    enabled: False
    n_splits: 20
    nbits: 512
    normalize_inputs: True
    return_predictions: True

  bioactivity:
    impl: chembench.metrics.Modelability
    datasets:
      - file: /workspace/cheminformatics/benchmark/csv_data/benchmark_ExCAPE_Bioactivity.csv
        impl: chembench.datasets.ExCAPEDataset
        label: excape
        index_col: index
        smis_col: SMILES
        load_cols:
          - SMILES
          - Gene_Symbol
        properties_cols:
          - pXC50
        orig_property_name:
          - null
        type: EMBEDDING
        variations:
          group_by: 'gene'
        input_size: null
    enabled: True
    gene_cnt: -1
    n_splits: 20
    nbits: 512
    normalize_inputs: True
    return_predictions: True

hydra:
  job_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: simple
        filename: /data/logs/benchmark.log
    root:
      level: INFO
      handlers: [console, file]
    disable_existing_loggers: false
