formatters:
  simple:
    format: '%(asctime)s %(name)s [%(levelname)s]: %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    stream: ext://sys.stdout

root:
  handlers: [console]

model:
  # name: MegaMolBART
  name: CDDD
  params:
    url: localhost:50051

metric:
  validity:
    enabled: True
    input_size: 20000
    radius:
      - 1
      - 2

  unique:
    enabled: True
    input_size: ${metric.validity.input_size}
    remove_invalid: True
    radius: ${metric.validity.radius}

  novelty:
    enabled: True
    input_size: ${metric.validity.input_size}
    remove_invalid: True
    radius: ${metric.validity.radius}

  nearest_neighbor_correlation:
    enabled: False
    input_size: ${metric.validity.input_size}
    top_k:
      - 50
      - 100
      - 500

  modelability:
    bioactivity:
      enabled: False
      input_size: -1 # Number of genes to include, not number of molecules
      n_splits: 20

    physchem:
      enabled: False
      input_size: ${metric.validity.input_size}
      n_splits: 20
  
sampling:
  max_seq_len: 512
  sample_size: 10

output:
  path: /data/benchmark_output/
