exp_name: benchmark
log:
  level: 10 # https://docs.python.org/3/library/logging.html#levels
model:
  name: nemo_chem.models.megamolbart.NeMoMegaMolBARTWrapper
  random_weights: False
  display_name: NeMoMegaMolBART
  training_data: /data/db/zinc_train.sqlite3
  batch_size: 50
  perceiver_average: False
  noise_mode: 2
  average_tokens: True

sampling:
  max_seq_len: 512
  sample_size: 10
  input_size: 1000
  db: /data/db/${exp_name}.sqlite3
  concurrent_requests: 10
  initialize_db: True
  radius:
    - 0.7

output:
  path: /data/benchmark_output/${exp_name}

metrics:
  validity:
    impl: chembench.metrics.Validity
    datasets:
      - file: /workspace/chembench/csv_data/benchmark_ZINC15_test_split.csv
        smis_col: canonical_smiles
        type: SAMPLE
        input_size: ${sampling.input_size}
        label: sample_ds
    enabled: True

  unique:
    impl: chembench.metrics.Unique
    datasets: ${metrics.validity.datasets}
    enabled: ${metrics.validity.enabled}
    remove_invalid: False

  novelty:
    impl: chembench.metrics.Novelty
    datasets: ${metrics.validity.datasets}
    enabled: ${metrics.validity.enabled}
    remove_invalid: False

  canonicalizeNovelty:
    impl: chembench.metrics.CanonicalizeNovelty
    datasets: ${metrics.validity.datasets}
    enabled: ${metrics.validity.enabled}
    remove_invalid: False

  effective_novelty:
    impl: chembench.metrics.EffectiveNovelty
    datasets: ${metrics.validity.datasets}
    enabled: ${metrics.validity.enabled}
    remove_invalid: False

  non_identicality:
    impl: chembench.metrics.NonIdenticality
    datasets: ${metrics.validity.datasets}
    enabled: ${metrics.validity.enabled}
    remove_invalid: False

  scaffold_unique:
    impl: chembench.metrics.ScaffoldUnique
    datasets: ${metrics.validity.datasets}
    enabled: ${metrics.validity.enabled}
    remove_invalid: False

  scaffold_non_identical_similarity:
    impl: chembench.metrics.ScaffoldNonIdenticalSimilarity
    datasets: ${metrics.validity.datasets}
    enabled: ${metrics.validity.enabled}
    remove_invalid: False
    nbits: 2048

  nearest_neighbor_correlation:
    impl: chembench.metrics.NearestNeighborCorrelation
    datasets:
      - file: /workspace/chembench/csv_data/benchmark_ChEMBL_approved_drugs_physchem.csv
        impl: chembench.datasets.base.GenericCSVDataset
        label: chembl
        properties_cols:
          - max_phase_for_ind
          - mw_freebase
          - alogp
          - hba
          - hbd
          - psa
          - rtb
          - ro3_pass
          - num_ro5_violations
          - cx_logp
          - cx_logd
          - full_mwt
          - aromatic_rings
          - heavy_atoms
          - qed_weighted
          - mw_monoisotopic
          - hba_lipinski
          - hbd_lipinski
          - num_lipinski_ro5_violations
        index_col: index
        smis_col: canonical_smiles
        type: EMBEDDING
        input_size: null
    nbits: 512
    enabled: True
    top_k:
      - 50
      - 100
      - 500

  physchem_lipophilicity:
    impl: chembench.metrics.Modelability
    datasets:
      - file: /workspace/chembench/csv_data/benchmark_MoleculeNet_Lipophilicity.csv
        impl: chembench.datasets.base.GenericCSVDataset
        label: lipophilicity
        index_col: index
        smis_col: SMILES
        properties_cols:
          - logD
        orig_property_name:
          - exp
        type: EMBEDDING
        input_size: null
    enabled: True
    y_randomize: False
    random_iterations: 10
    n_splits: 20
    nbits: 512
    normalize_inputs: True
    return_predictions: True

  physchem_esol:
    impl: chembench.metrics.Modelability
    datasets:
      - file: /workspace/chembench/csv_data/benchmark_MoleculeNet_ESOL.csv
        impl: chembench.datasets.base.GenericCSVDataset
        label: esol
        index_col: index
        smis_col: SMILES
        properties_cols:
          - 'log_solubility_(mol_per_L)'
        orig_property_name:
          - measured log solubility in mols per litre
        type: EMBEDDING
        input_size: null
    enabled: True
    y_randomize: False
    random_iterations: 10
    n_splits: 20
    nbits: 512
    normalize_inputs: True
    return_predictions: True

  physchem_freesolv:
    impl: chembench.metrics.Modelability
    datasets:
      - file: /workspace/chembench/csv_data/benchmark_MoleculeNet_FreeSolv.csv
        impl: chembench.datasets.base.GenericCSVDataset
        label: freesolv
        index_col: index
        smis_col: SMILES
        properties_cols:
          - hydration_free_energy
        orig_property_name:
          - y
        type: EMBEDDING
        input_size: null
    enabled: True
    y_randomize: False
    random_iterations: 10
    n_splits: 20
    nbits: 512
    normalize_inputs: True
    return_predictions: True

  bioactivity:
    impl: chembench.metrics.Modelability
    datasets:
      - file: /workspace/chembench/csv_data/benchmark_ExCAPE_Bioactivity.csv
        impl: chembench.datasets.ExCAPEDataset
        label: excape
        index_col: index
        smis_col: SMILES
        load_cols:
          - SMILES
          - Gene_Symbol
        properties_cols:
          - pXC50
        orig_property_name:
          - null
        type: EMBEDDING
        variations:
          group_by: 'gene'
        input_size: null
    enabled: True
    gene_cnt: -1
    n_splits: 20
    nbits: 512
    normalize_inputs: True
    return_predictions: True