formatters:
  simple:
    format: '%(asctime)s %(name)s [%(levelname)s]: %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    stream: ext://sys.stdout

root:
  handlers: [console]
  do_benchmark: False # set to True to run benchmark or False to skip model download etc, if only plots are needed
  do_plots: True # set to True to make plots, or False to skip

model:
  name: MegaMolBART #Latent #CDDD
  exp_name: prcvr_k4 #vae_k4 #mim_k1_salv # prcvr_k4 #seq2seq # mim_same_aug_k1 #
  checkpoint_file: Prcvr_SSA_no_mask_steps_4_Draco_nodes_4_gpus_16.nemo # VAE_SSA_steps_4_latent_dim_-1_Draco_nodes_4_gpus_16.nemo  # Base_Small_Span_Aug_Half_noam_Draco_nodes_4_gpus_16.nemo # MIM_SSA_steps_1_latent_dim_-1_same_aug_sample_logv.nemo # Base_Small_Span_Aug_Half_noam_Draco_nodes_4_gpus_16.nemo # VAE_SSA_steps_4_latent_dim_-1_Draco_nodes_4_gpus_16.nemo #Prcvr_SSA_no_mask_steps_4_Draco_nodes_4_gpus_16.nemo #Base_Small_Span_Aug_Half_noam_Draco_nodes_4_gpus_16.nemo MIM_SSA_steps_1_latent_dim_-1_same_aug_sample_logv.nemo
  training_data: /data/db/zinc_train_half.sqlite3 # /data/db/cddd_train.sqlite3 # 
  batch_size: 100 # 100 for seq2seq radii > 1 batch_size of 500 is too much for single GPU
  perceiver_average: False
  noise_mode: 0 # For LVM sampling selection default 0 for MIM 2

sampling:
  max_seq_len: 512
  sample_size: 10
  db: /data/db/embedding_cache_megamolbart_prcvr_k4_sampling_full_test.sqlite3 #embedding_cache_megamolbart_vae_k4_sampling_full.sqlite3
  concurrent_requests: 10

benchmark:
  metric_path: /data/benchmark_output/MegaMolBART/small_NeMo1.2_data_parallel

metric:
  validity:
    enabled: True
    input_size: 20000
    radius:
      - 1.2 #1.2 #1.2 # 0.7

  unique:
    enabled: True
    input_size: ${metric.validity.input_size}
    remove_invalid: False
    radius: ${metric.validity.radius}

  novelty:
    enabled: True
    input_size: ${metric.validity.input_size}
    remove_invalid: False
    radius: ${metric.validity.radius}

  effective_novelty:
    enabled: True
    input_size: ${metric.validity.input_size}
    remove_invalid: False
    radius: ${metric.validity.radius}

  non_identicality:
    enabled: True
    input_size: ${metric.validity.input_size}
    remove_invalid: False
    radius: ${metric.validity.radius}

  scaffold_unique:
    enabled: True
    input_size: ${metric.validity.input_size}
    remove_invalid: False
    radius: ${metric.validity.radius}
  
  scaffold_non_identical_similarity:
    enabled: True
    input_size: ${metric.validity.input_size}
    remove_invalid: False
    radius: ${metric.validity.radius}
    nbits: 2048

  scaffold_novelty:
    enabled: True
    input_size: ${metric.validity.input_size}
    remove_invalid: False
    radius: ${metric.validity.radius}

  effective_scaffold_novelty:
    enabled: True
    input_size: ${metric.validity.input_size}
    remove_invalid: False
    radius: ${metric.validity.radius}

  entropy:
    enabled: False
    input_size: ${metric.validity.input_size}
    radius: ${metric.validity.radius}

  nearest_neighbor_correlation:
    enabled: False
    input_size: -1
    top_k:
      - 50
      - 100
      - 500

  modelability:
    physchem:
      enabled: False
      input_size: -1
      n_splits: 20
      normalize_inputs: True
      return_predictions: True

    bioactivity:
      enabled: False
      input_size: -1 # Number of genes to include, not number of molecules, -1 is all genes
      gene_cnt: -1
      n_splits: 20
      normalize_inputs: True
      return_predictions: True

plotting:
  metric_paths:
    - /data/benchmark_output/nemo_20220714
    - /data/benchmark_output/nemo_20220720
  exp_name_list: # labels to append to model names for plotting, must be same number of elements as metric_paths
    - 'MegaMolBARTv0.2 (2022/07/14)'
    - 'MegaMolBARTv0.2 (2022/07/20)'
  acceptance_criteria:
    validity: 0.98
    novelty: 0.50
  limit_genes: 4 # limit the genes plotted -- int or list of gene names or null for all
  reports_dir: /data/benchmark_output/reports_test #/data/benchmark_output/plots
  save_plots: True
  max_seq_len: ${sampling.max_seq_len}
