formatters:
  simple:
    format: '%(asctime)s %(name)s [%(levelname)s]: %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    stream: ext://sys.stdout

root:
  handlers: [console]

model:
  # Please change following properties when changing model.name
  #   - sampling.concurrent_requests
  #   - model.params.url (50052 for lb grpc)
  # MegaMolBART Seq2Seq Base_Small_Span_Aug_Half_noam_Draco_nodes_4_gpus_16.nemo
  name: MegaMolBART #MegaMolBARTLatent # MegaMolBART
  exp_name: seq2seq
  checkpoint_file: Base_Small_Span_Aug_Half_noam_Draco_nodes_4_gpus_16.nemo #MIM_SSA_steps_1_latent_dim_-1_same_aug_sample_logv.nemo #Prcvr_SSA_no_mask_steps_4_Draco_nodes_4_gpus_16.nemo #Base_Small_Span_Aug_Half_noam_Draco_nodes_4_gpus_16.nemo
  training_data: /data/db/zinc_train_test.sqlite3 #/data/db/cddd_train.sqlit
  batch_size: 100 # 500 for seq2seq radii > 1 batch_size of 500 is too much for single GPU
  noise_mode: 2 # For LVM sampling selection

  # name:  cuchembench.inference.GrpcMegaMolBARTWrapper
  # training_data: /data/db/zinc_train.sqlite3
  # params:
  #   url: nginx:50052

sampling:
  max_seq_len: 512
  sample_size: 10
  db: /data/db/embedding_cache_megamolbart_seq2seq_1.2_bs_100.sqlite3 #mim_logv_k1_20k_500_bs.sqlite3
  concurrent_requests: 10

output:
#TODO: Change path for new models
  path: /data/benchmark_output/seq2seq #prcvr_k4 #use unique names here

metric:
  validity:
    enabled: True
    input_size: 20000
    radius:
      - 1.2
      # - 1

  unique:
    enabled: True
    input_size: ${metric.validity.input_size}
    remove_invalid: False
    radius: ${metric.validity.radius}

  novelty:
    enabled: True
    input_size: ${metric.validity.input_size}
    remove_invalid: False
    radius: ${metric.validity.radius}

  effective_novelty:
    enabled: True
    input_size: ${metric.validity.input_size}
    remove_invalid: False
    radius: ${metric.validity.radius}

  identicality:
    enabled: True
    input_size: ${metric.validity.input_size}
    remove_invalid: False
    radius: ${metric.validity.radius}

  nearest_neighbor_correlation:
    enabled: False
    input_size: -1
    top_k:
      - 50
      - 100
      - 500

  modelability:
    physchem:
      enabled: False
      input_size: -1
      n_splits: 20
      normalize_inputs: True
      return_predictions: True

    bioactivity:
      enabled: False
      input_size: -1 # Number of genes to include, not number of molecules, -1 is all genes
      gene_cnt: -1
      n_splits: 20
      normalize_inputs: True
      return_predictions: True
