version: "3.9"

networks:
  cuchemNet:
    driver: bridge
    ipam:
      config:
        - subnet: 192.167.100.0/16

services:
  cuchemUI:
    image: "${CUCHEM_CONT}"
    hostname: cuchemUI
    networks:
      cuchemNet:
        ipv4_address: 192.167.100.1
    ports:
      - "5000:5000"
    volumes:
      - './:/workspace'
      - "${DATA_PATH}:/data"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
    working_dir: /workspace
    command: ./launch.sh start ${ADDITIONAL_PARAM}
    extra_hosts:
      - "megamolbart:192.167.100.2"

  megamolbart:
    image: "${MEGAMOLBART_CONT}"
    hostname: 'megamolbart'
    networks:
      cuchemNet:
        ipv4_address: 192.167.100.2
    volumes:
        - './:/workspace'
        - "${DATA_PATH}:/data"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]