version: "3.9"

networks:
  cuchemNet:
    name: cuchemNet${RUN_ID}
    driver: bridge
    ipam:
      config:
        - subnet: ${SUBNET}

services:
  cuchemUI:
    container_name: cuchemUI${RUN_ID}
    image: "${CUCHEM_CONT}"
    hostname: cuchemUI
    user: $UID:$GID
    environment:
      - CUPY_CACHE_DIR=/workspace/.cupy/kernel_cache
      - PYTHONPATH=${PYTHONPATH_CUCHEM}
    networks:
      cuchemNet:
        ipv4_address: ${IP_CUCHEM_UI}
    ports:
      - "${PLOTLY_PORT}:5000"
    volumes:
      - "./:/workspace"
      - "${CONTENT_PATH}/data:/data"
      - "${CONTENT_PATH}/logs:/logs"
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - /etc/shadow:/etc/shadow:ro
    working_dir: ${WORKING_DIR_CUCHEMUI}
    command: ${CUCHEM_UI_START_CMD}
    extra_hosts:
      - "megamolbart:${IP_MEGAMOLBART}"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]

  megamolbart:
    container_name: megamolbart${RUN_ID}
    image: "${MEGAMOLBART_CONT}"
    hostname: 'megamolbart'
    user: $UID:$GID
    environment:
      - PYTHONPATH=${PYTHONPATH_MEGAMOLBART}
    networks:
      cuchemNet:
        ipv4_address: ${IP_MEGAMOLBART}
    volumes:
      - './:/workspace'
      - "${CONTENT_PATH}/data:/data"
      - "${CONTENT_PATH}/models:/models"
      - "${CONTENT_PATH}/logs:/logs"
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - /etc/shadow:/etc/shadow:ro
    working_dir: ${WORKING_DIR_MEGAMOLBART}
    command: ${MEGAMOLBART_CMD}
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]